site_title = "ArxivDaily"
limit_days = 7
cache_url = "https://li-yang23.github.io/ArxivDaily/cache.json"

[[sources]]
limit = 100
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 100
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 100
category = "cs.CR"
title = "Cryptography and Security"

[[sources]]
limit = 100
category = "cs.LG"
title = "Machine Learning"

# [[sources]]
# limit = 100
# category = "cs.MM"
# title = "Multimedia"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
